### ISSUE TITLE
Experiencing 403 Errors in CI Test Builds

### ISSUE THREAD

**Issue by nickviola** [cisagov/li-pca-app-docker#8]
# 🐛 Summary #

On the first commits branch in PR: Experiencing the following error on CI test builds: `Error: buildx failed with: error: failed to solve: unexpected status: 403 Forbidden` 

CI Results: https://github.com/cisagov/li-pca-app-docker/runs/5100731166?check_suite_focus=true

Possible solution research: https://github.com/docker/build-push-action/issues/463#issuecomment-924995909
## To reproduce ##

1. Re-run jobs in Github CI Workflow
2. Check output of CI for 403 errors.

## Expected behavior ##

Tests build successfully without 403 errors.

## Any helpful log output or screenshots ##

Paste the results here:

```console
Error: buildx failed with: error: failed to solve: unexpected status: 403 Forbidden```

Add any screenshots of the problem here.

**Comment by dav3r** [comment]
@nickviola - I believe this problem is happening because you are attempting to overwrite the `cisagov/example` Docker image, which you don't have permission to.  You need to change this line from to `cisagov/example` to `cisagov/li-pca-app`:
https://github.com/cisagov/li-pca-app-docker/blob/a80f7cc66ed37fa52b2f5210acbe3f0a78eb6a0f/.github/workflows/build.yml#L30

I also noticed some places in this branch where you refer to this image as `li-pca-app-docker`.  I recommend that you change all of those to `li-pca-app`, since the "-docker" part isn't adding any value.

**Comment by nickviola** [comment]
Thanks @dav3r. I'm giving this a try. Thank you for taking a look at this so quickly. We greatly appreciate your help!

**Comment by nickviola** [comment]
403 errors resolved by changing the IMAGE_NAME value per @dav3r's suggestion above.  

Commit: 0f19b229b6222729bd3a5809a4eeda20f646ab0d

**Comment by dav3r** [comment]
Glad to hear that did the trick!
